export const SET_UG = 'SET_UG'
export const SET_MEETUP = 'SET_MEETUP_TITLE'
export const SET_TALK = 'SET_TALK_TITLE'
export const OPEN_SETTINGS_DIALOG = 'OPEN_SETTINGS_DIALOG'
export const CLOSE_SETTINGS_DIALOG = 'CLOSE_SETTINGS_DIALOG'
export const SAVE_SETTINGS = 'SAVE_SETTINGS';

